[package]
name = "wii-crypto"
version = "0.1.0"
authors = ["kipcode66 <egamer1010@gmail.com>"]

[dependencies]
byteorder = "1.3.4"
lazy_static = "1.4.0"
block-modes = "0.7.0"
aes = "0.6.0"
rayon = "1.5.0"
#pbr = "1.0.3"
